// app/layout.tsx
import './globals.css'
import type { Metadata } from 'next'

// Font imports
import { Inter, Space_Grotesk } from 'next/font/google'

// Font configs
const inter = Inter({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-inter',
})

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-space-grotesk',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`bg-black ${inter.variable} ${spaceGrotesk.variable}`}>
      <body className="bg-black">
        {children}
      </body>
    </html>
  )
}