// app/layout.tsx
import './globals.css'
import type { Metadata } from 'next'

// Font imports
import { Kanit, Manrope, Mea_Culpa, IBM_Plex_Sans, Rajdhani } from 'next/font/google'

// Font configs
const kanit = Kanit({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-kanit',
})

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-manrope',
})

const meaCulpa = Mea_Culpa({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-mea-culpa',
})

const ibmSans = IBM_Plex_Sans({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  variable: '--font-ibm-sans',
})

const rajdhani = Rajdhani({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-rajdhani',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`bg-black ${kanit.variable} ${manrope.variable} ${meaCulpa.variable} ${ibmSans.variable} ${rajdhani.variable}`}>
      <body className="bg-black">
        {children}
      </body>
    </html>


  )
}

